Clarify CLI instructions
sveltejs/cli pull request #212
Opened 2024-10-23 03:24 UTC by sacrosanctic

related conversation
https://discord.com/channels/457912077277855764/1298479734606528628

2024-10-23 03:48 UTC, AdrianGonz97 approved these changes
thanks!

2024-10-23 10:33 UTC, benmccann commented on packages/cli/commands/add/index.ts
> +			message: `What would you like to add to your project? ${pc.dim('(use arrow keys/space bar)')}`,
```suggestion
			message: `What would you like to add to your project? ${pc.dim('(use arrow keys / space bar)')}`,
```

2024-10-23 10:34 UTC, benmccann commented
Do we need the same hint if you run `create`, etc ?

2024-10-23 13:52 UTC, AdrianGonz97 commented
this change is already shared with `create` since as it invokes `runAddCommand`

2024-10-23 13:56 UTC, benmccann requested changes
Oh, that's pretty weird. You'd want it to show up in the first create question - not the third

2024-10-23 13:58 UTC, AdrianGonz97 commented
it only shows up on the multi-select where there's a difference between `space` and `enter`. the others are just normal select prompts

2024-10-23 17:13 UTC, manuel3108 commented
I also understand it the way that the core problem is the multiselect. 
But I think we should be consistent and also add it to the tailwind plugin multiselect:

![image](https://github.com/user-attachments/assets/234879e3-76b8-4a1b-a532-c4c869f63ddf)

2024-10-23 17:16 UTC, AdrianGonz97 commented
I thought about that and figured that it's fine to exclude it from proceeding multi-select prompts as you've been "taught" what to do by the time you reach this prompt

2024-10-23 17:39 UTC, sacrosanctic commented
What is the reason for not adding hints to subsequent multi-selects? Is it because of clutter?

Isn't it always better to provide visual aid, I understand it's squares for multi-select and circles for single-select. But I find that hardly noticeable.

2024-10-23 18:02 UTC, benmccann commented
I'd have to see what it looks like, but my first reaction is that it'd be too noisy and we should mention it only once

2024-10-23 18:36 UTC, AdrianGonz97 commented
seeing it now, I still think it adds unnecessary noise. this noisiness is also exacerbated when the instructions are kept on screen long after prompt submission

2024-10-23 19:13 UTC, sacrosanctic commented
Is it possible to add a check to only show the hint on the first multi-select  the user encounters, or would that increase the code complexity.

If possible, this would reduce clutter and still have hints regardless of which branch the user takes.

2024-10-24 15:57 UTC, manuel3108 approved these changes

2024-10-24 16:00 UTC, manuel3108 commented
Let's only add this to the integration-selection question for now, as everyone seems to agree there. Let's get this merged and hear for user feedback

2024-10-24 16:01 UTC, merged