fix: use `vite@5`
sveltejs/cli pull request #353
Opened 2024-12-11 17:11 UTC by manuel3108

Relates #341, https://github.com/sveltejs/cli/pull/311#issuecomment-2531023527

From https://github.com/vitest-dev/vitest/issues/7014#issuecomment-2527453004
> Vitest 2 doesn't support Vite 6 and will not support Vite 6 officially. You can use resolutions or pnpm.overrides to change the version range locally, Vite 6 API is the same and should work for Vitest 2.
> 
> If you migrated to Vite 6, use Vitest 3 (currently in beta), release is planned for January.
> 
> If you see any type errors in your config, check the lockfile to confirm that you have several Vite versions installed and resolve it with your package manager.

2024-12-16 18:02 UTC, AdrianGonz97 requested changes

2024-12-16 18:02 UTC, AdrianGonz97 commented on packages/create/templates/demo/package.json
> +		"vite": "^5.3.2"
```suggestion
		"vite": "^5.4.11"
```

2024-12-16 18:02 UTC, AdrianGonz97 commented on packages/create/templates/demo/package.template.json
> +		"vite": "^5.0.3"
```suggestion
		"vite": "^5.4.11"
```

2024-12-16 18:02 UTC, AdrianGonz97 commented on packages/create/templates/library/package.template.json
> +		"vite": "^5.0.11"
```suggestion
		"vite": "^5.4.11"
```

2024-12-16 18:02 UTC, AdrianGonz97 commented on packages/create/templates/minimal/package.template.json
> +		"vite": "^5.0.3"
```suggestion
		"vite": "^5.4.11"
```

2024-12-20 09:14 UTC, dominikg commented
whats missing to get this merged?

2024-12-20 18:07 UTC, Rich-Harris commented
preview: https://svelte-dev-git-preview-cli-353-svelte.vercel.app/

_this is an automated message_

2024-12-20 18:15 UTC, merged

2025-01-18 01:54 UTC, hyunbinseo commented
Vitest 3.0 with Vite 6 support has been released.

- https://vitest.dev/blog/vitest-3
- https://github.com/vitest-dev/vitest/releases/tag/v3.0.0